name: Update AList binary

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: alist-org/alist
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract AList binary
        run: |
          wget "https://github.com/alist-org/alist/releases/download/${{ steps.get-latest-release.outputs.release }}/alist-linux-amd64.tar.gz" -O alist-linux-amd64.tar.gz
          tar -zxvf "alist-linux-amd64.tar.gz" --overwrite
          rm "alist-linux-amd64.tar.gz"

      - name: Commit and push changes if necessary
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "${{ steps.get-latest-release.outputs.release }}"
          git push